### ISSUE TITLE
Sjekke sikkerhetsstatus på Unleash v3

### ISSUE THREAD

**Issue by mortenlj** [nais/unleash#32]
Finne ut hvordan stå er, slik at vi kan gjøre en vurdering på om vi bare skal fortsette med v3 en stund til, eller om vi må ta tak i oppgradering til v4.

**Comment by Starefossen** [comment]
Jeg har oppgradert sårbare npm pakker til siste patch versjon og rullet dette ut.

**Comment by jksolbakken** [comment]
Det er ingen aktivitet på noen 3.x brancher siden påsketider i 2021, lukter vel fort litt v4 da...

**Comment by Starefossen** [comment]
Det er min konklusjon også og har så vidt begynt å leke på tanken med en unleasherator for å la teamene sette opp sine egne unleash instanser 🚀

**Comment by jksolbakken** [comment]
"togglorator"

**Comment by jksolbakken** [comment]
Denne biten med å sjekke status er vel da strengt tatt ferdig, setter til "done"

**Comment by mortenlj** [comment]
Høres ut som vi bør lage oss en ny lapp for å faktisk gjøre løftet som ser ut til å være nødvendig.

**Comment by mortenlj** [comment]
https://github.com/nais/unleash/issues/41
