### ISSUE TITLE
Finne ut hvordan vi vil løse Unleash v4

### ISSUE THREAD

**Issue by mortenlj** [nais/unleash#41]

**Comment by Starefossen** [comment]
Jeg har sett litt på en Unleash Operator ([nais/unleasherator](https://github.com/nais/unleasherator) fordi det er ønskelig at teamene får sin egen installasjon av Unleash slik at ikke alle går og tråkker på hver andre sine feature toggles.

Men så har jeg ikke helt en klar løsning for hvor teamene sin installasjon av Unleash skal ligge, for jeg tror ikke det er helt ønskelig at man får en installasjon av Unleash per team per cluster, men heller at man har 1 unleash instans globalt per team.


```mermaid
graph
  subgraph unleash
    unleash-a
    unleash-b
  end

  subgraph dev-gcp
     subgraph dev-gcp-team-a[team-a]
       dev-gcp-team-a-app[pod]-->unleash-a
     end
     subgraph dev-gcp-team-b[team-b]
       dev-gcp-team-b-app[pod]-->unleash-b
     end
  end

  subgraph prod-gcp
     subgraph prod-gcp-team-a[team-a]
       prod-gcp-team-a-app[pod]-->unleash-a
     end
     subgraph prod-gcp-team-b[team-b]
       prod-gcp-team-b-app[pod]-->unleash-b
     end
  end
```
